services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/data:/app/src/data
      - ./backend/storage:/app/storage
    ports:
      - "5001:5001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5000:80"
